import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "BogdanGPT - Chat with GPT",
  description: "Generated by CHAT GPT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en" className="min-h-screen">
      <body
        className={`${josefin.className} p-20 flex justify-center items-center w-full min-h-screen bg-gradient-to-b from-orange-400 to-orange-200`}
      >
        {children}
      </body>
    </html>
  );
}
